title: Iffah Khoirul Janah
logo: /assets/img/pasfoto.png
description: Mahasiswa Manajemen Informasi Kesehatan, Universitas Gadjah Mada

social_links:
  email: "mailto:iffahkhoiruljanah@mail.ugm.ac.id"
  instagram: "https://www.instagram.com/iffah_khoirul"
  github: "https://github.com/iffahkhr"

theme: jekyll-theme-minimal
