title: Iffah Khoirul Janah
logo: /assets/img/pasfoto_circle.png
description: Mahasiswa Manajemen Informasi Kesehatan Sekolah Vokasi Universitas Gadjah Mada
minima:
  social_links:
    - icon: github
      url: "https://github.com/iffahkhr/"
    - icon: instagram
      url: "https://www.instagram.com/iffah_khoirul"
    - icon: mail
      url: "iffahkhoiruljanah@mail.ugm.ac.id"    
theme: jekyll-theme-minimal
