title: Iffah Khoirul Janah
profile_image: /img/pasfoto.png
description: Mahasiswa Manajemen Informasi Kesehatan 
description: Universitas Gadjah Mada
social:
  email: "iffahkhoiruljanah@mail.ugm.ac.id"   
  instagram: "https://www.instagram.com/iffah_khoirul"
  github: "https://github.com/iffahkhr/"
theme: jekyll-theme-minimal
