author:
  name: "Iffah Khoirul Janah"
  title: "Mahasiswa Manajemen Informasi Kesehatan, Universitas Gadjah Mada"
  image: "/assets/profile.jpg"
  cv_link: "/cv.pdf"
  email: "mailto:iffahkhoiruljanah@mail.ugm.ac.id"
  instagram: "https://www.instagram.com/iffah_khoirul"
  github: "https://github.com/iffahkhr"

theme: jekyll-theme-minimal
